apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: amanjaiswal144181/processor
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/credentials.json
              name: google-cloud-key
              subPath: credentials.json
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/credentials.json
      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-credentials